// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class NativeLocationData {
  NativeLocationData({
    required this.positionLatitude,
    required this.positionLongitude,
    required this.positionAccuracy,
    required this.elevationAltitude,
    required this.elevationAccuracy,
    required this.headingDirection,
    required this.headingAccuracy,
    required this.courseDirection,
    required this.courseAccuracy,
    required this.speedMagnitude,
    required this.speedAccuracy,
    required this.timestamp,
  });

  double positionLatitude;

  double positionLongitude;

  double positionAccuracy;

  double elevationAltitude;

  double elevationAccuracy;

  double headingDirection;

  double headingAccuracy;

  double courseDirection;

  double courseAccuracy;

  double speedMagnitude;

  double speedAccuracy;

  String timestamp;

  List<Object?> _toList() {
    return <Object?>[
      positionLatitude,
      positionLongitude,
      positionAccuracy,
      elevationAltitude,
      elevationAccuracy,
      headingDirection,
      headingAccuracy,
      courseDirection,
      courseAccuracy,
      speedMagnitude,
      speedAccuracy,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeLocationData decode(Object result) {
    result as List<Object?>;
    return NativeLocationData(
      positionLatitude: result[0]! as double,
      positionLongitude: result[1]! as double,
      positionAccuracy: result[2]! as double,
      elevationAltitude: result[3]! as double,
      elevationAccuracy: result[4]! as double,
      headingDirection: result[5]! as double,
      headingAccuracy: result[6]! as double,
      courseDirection: result[7]! as double,
      courseAccuracy: result[8]! as double,
      speedMagnitude: result[9]! as double,
      speedAccuracy: result[10]! as double,
      timestamp: result[11]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLocationData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeLocationData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeLocationData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FusedLocationHostApi {
  /// Constructor for [FusedLocationHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FusedLocationHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startLocationUpdates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fused_location.FusedLocationHostApi.startLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopLocationUpdates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fused_location.FusedLocationHostApi.stopLocationUpdates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class FusedLocationFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onLocationUpdate(NativeLocationData location);

  static void setUp(FusedLocationFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.fused_location.FusedLocationFlutterApi.onLocationUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.fused_location.FusedLocationFlutterApi.onLocationUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final NativeLocationData? arg_location = (args[0] as NativeLocationData?);
          assert(arg_location != null,
              'Argument for dev.flutter.pigeon.fused_location.FusedLocationFlutterApi.onLocationUpdate was null, expected non-null NativeLocationData.');
          try {
            api.onLocationUpdate(arg_location!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
